mac: do not separate admin/user domains
Building search list for them leads to
https://youtrack.jetbrains.com/issue/IJPL-190650 (System wide certificates not read by Gateway/IntelliJ/JB Client 2025.1.1 and above in macOS)

java.lang.IllegalStateException: SecItemCopyMatching failed: The specified item could not be found in the keychain.
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.copyMatchingCertificates(SecurityFrameworkUtil.java:99)
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.getTrustedRoots(SecurityFrameworkUtil.java:37)
	at org.jetbrains.nativecerts.NativeTrustedCertificates.getCustomOsSpecificTrustedCertificates(NativeTrustedCertificates.java:34)
	at com.intellij.util.net.ssl.OsCertificatesServiceImpl.getCustomOsSpecificTrustedCertificates(OsCertificatesServiceImpl.java:20)

so it's easier not to query them separately